apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gitpulse.fullname" . }}
  labels:
    {{- include "gitpulse.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "gitpulse.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "gitpulse.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "gitpulse.fullname" . }}
      automountServiceAccountToken: true
      {{- with .Values.imagePullSecret }}
      imagePullSecrets:
        - name: {{ . }}
      {{- end }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: {{ .Values.service.targetPort | quote }}
            - name: HOSTNAME
              value: "0.0.0.0"
          envFrom:
            - secretRef:
                name: {{ .Values.secrets.name }}
          startupProbe:
            httpGet:
              path: /api/health
              port: http
            failureThreshold: 10
            periodSeconds: 3
          livenessProbe:
            httpGet:
              path: /api/health
              port: http
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/health
              port: http
            periodSeconds: 10
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
