{{- if .Values.ingress.domain }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "gitpulse.fullname" . }}
  labels:
    {{- include "gitpulse.labels" . | nindent 4 }}
  annotations:
    alb.ingress.kubernetes.io/scheme: "internet-facing"
    alb.ingress.kubernetes.io/target-type: "ip"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  rules:
    - host: {{ .Values.ingress.domain | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "gitpulse.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
{{- end }}
