apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "gitpulse.fullname" . }}
  labels:
    {{- include "gitpulse.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: false
